// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2sIExTW4jfstAnXOWfwDiKuTBxIJMFM',
    appId: '1:51262403977:web:79f4c3033dd12d0baf5d58',
    messagingSenderId: '51262403977',
    projectId: 'cliapp-7b908',
    authDomain: 'cliapp-7b908.firebaseapp.com',
    storageBucket: 'cliapp-7b908.appspot.com',
    measurementId: 'G-TBCNKG0T2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPbKsvn8oRYe98T0pb-WNjlcEPVmHb7s',
    appId: '1:51262403977:android:b2d52d52d6aa1287af5d58',
    messagingSenderId: '51262403977',
    projectId: 'cliapp-7b908',
    storageBucket: 'cliapp-7b908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNU2lRfeJgQdMPzJjJR4WSmpwPtwcMUg',
    appId: '1:51262403977:ios:234d7c4c173c6544af5d58',
    messagingSenderId: '51262403977',
    projectId: 'cliapp-7b908',
    storageBucket: 'cliapp-7b908.appspot.com',
    iosBundleId: 'com.example.appUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNU2lRfeJgQdMPzJjJR4WSmpwPtwcMUg',
    appId: '1:51262403977:ios:b840d7a08872c3ecaf5d58',
    messagingSenderId: '51262403977',
    projectId: 'cliapp-7b908',
    storageBucket: 'cliapp-7b908.appspot.com',
    iosBundleId: 'com.example.appUi.RunnerTests',
  );
}
